POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "test2@test.com",
      "password": "12345678"
}

###
POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12345678",
  "username": "test222"
}

###
PUT http://localhost:8080/api/users/
Content-Type: application/json

{
  "username": "test2211",
  "bio": "test bio23",
  "image": "test image231"
}

###
GET http://localhost:8080/api/users/

###
GET http://localhost:8080/api/articles?limit=20&offset=0

###
GET http://localhost:8080/api/profiles/test2211

###
POST http://localhost:8080/api/profiles/test22/follow

###
DELETE http://localhost:8080/api/profiles/test22/follow

###
POST http://localhost:8080/api/articles
Content-Type: application/json

{
  "title": "How to train your dragon3",
  "description": "Ever wonder how?",
  "body": "You have to believe",
  "tagList": ["reactjs"]
}