POST http://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "test@test.com",
      "password": "12345678"
}

###
POST http://localhost:8080/api/users/
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678",
  "username": "test"
}

###
PUT http://localhost:8080/api/users/
Content-Type: application/json

{
  "username": "test2",
  "bio": "test bio",
  "image": "test image"
}

###
GET http://localhost:8080/api/auth/me

